// Forward-samples the Eczema BN and writes public/datasets/eczema.arff
// Run: node scripts/generate-eczema.js
// CPTs are the exact values from the probabilistic.net builder example.

const fs   = require('fs');
const path = require('path');

// Eczema BN CPTs
// Barrier <- [Gen, Det];  key = gen_bit + det_bit
const P_BARRIER = { '00': 0.05, '10': 0.40, '01': 0.30, '11': 0.75 };
// Th2 <- [Gen, DM, Diet]; key = gen_bit + dm_bit + diet_bit
const P_TH2 = {
  '000': 0.04, '100': 0.30, '010': 0.18, '110': 0.55,
  '001': 0.22, '101': 0.55, '011': 0.42, '111': 0.85,
};
// Flare <- [Barrier, Th2]; key = barrier_bit + th2_bit
const P_FLARE = { '00': 0.03, '10': 0.38, '01': 0.32, '11': 0.88 };

function b(p) { return Math.random() < p; }

function sample() {
  const gen     = b(0.25);
  const det     = b(0.60);
  const dm      = b(0.55);
  const diet    = b(0.65);
  const barrier = b(P_BARRIER[`${+gen}${+det}`]);
  const th2     = b(P_TH2[`${+gen}${+dm}${+diet}`]);
  const flare   = b(P_FLARE[`${+barrier}${+th2}`]);
  return [gen, det, dm, diet, barrier, th2, flare].map(v => v ? 'yes' : 'no');
}

const N = 500;
const rows = Array.from({ length: N }, sample);

const arff = `% Eczema / Atopic Dermatitis — synthetic dataset
% Forward-sampled from a 7-node Bayesian Network.
% True structure:
%   GeneticRisk, IrritantProducts  -> BrokenSkinBarrier
%   GeneticRisk, DustMiteExposure, HighSugarDiet -> Th2Dysregulation
%   BrokenSkinBarrier, Th2Dysregulation -> EczemaFlare
% Generated by: scripts/generate-eczema.js
% Instances: ${N}

@relation eczema

@attribute GeneticRisk        {yes,no}
@attribute IrritantProducts   {yes,no}
@attribute DustMiteExposure   {yes,no}
@attribute HighSugarDiet      {yes,no}
@attribute BrokenSkinBarrier  {yes,no}
@attribute Th2Dysregulation   {yes,no}
@attribute EczemaFlare        {yes,no}

@data
${rows.map(r => r.join(',')).join('\n')}
`;

const out = path.join(__dirname, '..', 'public', 'datasets', 'eczema.arff');
fs.writeFileSync(out, arff);
console.log(`Written ${N} instances to ${out}`);
// Print class distribution
const yes = rows.filter(r => r[6] === 'yes').length;
console.log(`EczemaFlare: yes=${yes} (${(yes/N*100).toFixed(1)}%), no=${N-yes} (${((N-yes)/N*100).toFixed(1)}%)`);
